routes/web.php
<?php

Auth::routes([
    'register' => false, // Registration Routes...
    'reset' => false, // Password Reset Routes...
    'verify' => false, // Email Verification Routes...
]);


Route::get('/', 'HomeController@index'); 

// bisa di arahakan ke front end sebenarnya
// Route::get('/', function () {
//     return view('home');
// });
    
Route::group(['middleware' => 'auth'], function(){
    Route::get('/mesin/cari', 'mesinController@search');
    Route::resource('mesin', 'mesinController');
    Route::post('/tipe/import_excel', 'tipeController@import_excel')->name('tipe.import_excel');
    Route::get('/tipe/cari', 'tipeController@search');
    Route::post('/tipe/hapus-semua', 'tipeController@hapusSemua')->name('tipe.hapusSemua'); 
    Route::resource('tipe', 'tipeController');
    Route::get('/jadwal-mesin/grup', 'jadwal_mesinController@grup');
    Route::get('/jadwal-mesin/cari-tanggal', 'jadwal_mesinController@cariTanggal');
    Route::resource('jadwal-mesin', 'jadwal_mesinController');
    Route::get('/rencana-produksi-live', 'rencana_produksiController@live')->name('rencana-produksi.live'); 
    Route::get('/rencana-produksi-live-export', 'rencana_produksiController@live_export')->name('rencana-produksi.live-export'); 
    Route::get('/rencana-produksi-live-info', 'rencana_produksiController@live_info')->name('rencana-produksi.live-info'); 
    Route::get('/rencana-produksi/cetak-laporan', 'rencana_produksiController@cetak')->name('cetak-laporan'); 
    Route::get('/rencana-produksi/export-csv', 'rencana_produksiController@exportcsv')->name('export-csv'); 
    Route::get('/rencana-produksi/cetak-spk/{id}', 'rencana_produksiController@cetak_spk')->name('rencana-produksi.cetak_spk'); 
    Route::post('/rencana-produksi/updatestatus/{id}', 'rencana_produksiController@updateStatus')->name('update_status');
    Route::get('/rencana-produksi/generate-next/{id}', 'rencana_produksiController@generateNext')->name('rencana-produksi.generateNext'); 
    Route::post('/rencana-produksi/upload', 'rencana_produksiController@upload')->name('rencana-produksi.upload');
    Route::post('/rencana-produksi/deleteattachment/{id}', 'rencana_produksiController@deleteattachment')->name('rencana-produksi.deleteattachment');
    Route::post('/rencana-produksi/addnote', 'rencana_produksiController@addnote')->name('rencana-produksi.addnote');
   
    Route::get('/rencana-produksi/{id}/edit-ng', 'rencana_produksiController@editNG')->name('rencana-produksi.edit_ng');
    Route::post('/rencana-produksi/update-ng/{id}', 'rencana_produksiController@updateNG')->name('rencana-produksi.update_ng');
    Route::get('/rencana-produksi/backup-button}', 'rencana_produksiController@backupButton')->name('rencana-produksi.backup_button');
    Route::post('/rencana-produksi/backup-button-post', 'rencana_produksiController@backupButtonPost')->name('rencana-produksi.bakcup_button_post');

    Route::post('/jadwal/hapus-semua', 'istirahatMesinController@hapusSemua')->name('jadwal-istirahat.hapusSemua'); 
    Route::post('/jadwal-istirahat/import_excel', 'istirahatMesinController@import_excel')->name('jadwal-istirahat.import_excel'); 
    Route::post('/jadwal-istirahat/generate', 'istirahatMesinController@generate')->name('jadwal-istirahat.generate'); 
    Route::resource('jadwal-istirahat', 'istirahatMesinController');
    Route::resource('rencana-produksi', 'rencana_produksiController');
    Route::resource('draft-rencana-produksi', 'rencana_produksiControllerDraft');
    Route::resource('perubahan-rencana-produksi', 'rencana_produksiControllerCache');
    Route::get('/laporan/cetak-laporan-injection', 'laporanController@cetak')->name('cetaklaporaninjection'); 
    Route::resource('laporan', 'laporanController');
    Route::resource('shifts', 'shiftController'); 
    Route::post('/shifts/upload-attachment', 'shiftController@upload')->name('shift.upload-attachment');
    Route::post('/shifts/delete-attachment/{id}', 'shiftController@deleteattachment')->name('shifts.delete-attachment');

    Route::resource('users', 'UserController')->middleware('auth');
    Route::resource('shiftSettings', 'shift_settingController');
    Route::resource('infos', 'infoController');
    Route::resource('listShifts', 'list_shiftController');

    Route::post('/outstandings/updatestatus/{id}', 'outstandingController@updateStatus')->name('outstandings.update_status');
    Route::post('/outstandings/import_excel', 'outstandingController@import_excel')->name('outstandings.import_excel');
    Route::resource('outstandings', 'outstandingController');

    Route::post('/outstandingItems/import_excel', 'outstanding_itemController@import_excel')->name('outstandingItems.import_excel');
    Route::resource('outstandingItems', 'outstanding_itemController');
    
    Route::post('/ppics/close-ppic', 'ppicController@close_ppic')->name('ppicController.close_ppic');
    Route::resource('ppics', 'ppicController');
    Route::resource('ppicLogs', 'ppic_logController');
    Route::resource('ppicComments', 'ppic_commentController');
    Route::resource('report-daily-stock', 'report_daily_stockController');

    Route::post('/daily-stocks/updatestatus/{id}', 'daily_stockController@updateStatus')->name('daily-stocks.update_status');
    Route::resource('daily-stocks', 'daily_stockController');

    Route::get('/notifications/updatestatus/{id}', 'notificationController@updateStatus')->name('notifications.update_status');
    Route::resource('notifications', 'notificationController');
    
    Route::post('/daily-stock-item/import_excel', 'daily_stock_itemController@import_excel')->name('daily-stock-item.import_excel');
    Route::resource('dailyStockItems', 'daily_stock_itemController');

    Route::get('/laporan/cetak-laporan-injection', 'laporanController@cetak')->name('cetaklaporaninjection'); 
    Route::resource('attachments', 'attachmentsController');

});

Route::group(['middleware' => 'App\Http\Middleware\SuperVisorMiddleWare'], function(){
    Route::resource('users', 'UserController')->middleware('auth');
});

?>

app/Models/daily_stock_item.php
<?php

namespace App\Models;

use Eloquent as Model;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * Class daily_stock_item
 * @package App\Models
 * @version September 11, 2022, 12:55 pm WIB
 *
 * @property integer $daily_stock_id
 * @property integer $type_id
 * @property integer $stock
 */
class daily_stock_item extends Model
{
    // use SoftDeletes;

    public $table = 'daily_stock_items';
    

    protected $dates = ['deleted_at'];



    public $fillable = [
        'daily_stock_id',
        'type_id',
        'stock',
        'error'
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'id' => 'integer',
        'daily_stock_id' => 'integer',
        'type_id' => 'integer',
        'stock' => 'integer',
        'error' => 'string'
    ];

    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = [
        
    ];

    public function type(){
        return $this->belongsTo(\App\Models\tipe::class, 'type_id');
    }
    
}

app/Http/Controllers/daily_stock_itemController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\Createdaily_stock_itemRequest;
use App\Http\Requests\Updatedaily_stock_itemRequest;
use App\Repositories\daily_stock_itemRepository;
use App\Http\Controllers\AppBaseController;
use Illuminate\Http\Request;
use Flash;
use Response;
use App\Imports\StockImport;
use Maatwebsite\Excel\Facades\Excel;

class daily_stock_itemController extends AppBaseController
{
    /** @var  daily_stock_itemRepository */
    private $dailyStockItemRepository;

    public function __construct(daily_stock_itemRepository $dailyStockItemRepo)
    {
        $this->dailyStockItemRepository = $dailyStockItemRepo;
    }

    /**
     * Display a listing of the daily_stock_item.
     *
     * @param Request $request
     *
     * @return Response
     */
    public function index(Request $request)
    {
        $dailyStockItems = $this->dailyStockItemRepository->all();

        return view('daily_stock_items.index')
            ->with('dailyStockItems', $dailyStockItems);
    }

    /**
     * Show the form for creating a new daily_stock_item.
     *
     * @return Response
     */
    public function create()
    {
        return view('daily_stock_items.create');
    }

    /**
     * Store a newly created daily_stock_item in storage.
     *
     * @param Createdaily_stock_itemRequest $request
     *
     * @return Response
     */
    public function store(Createdaily_stock_itemRequest $request)
    {
        $input = $request->all();

        $dailyStockItem = $this->dailyStockItemRepository->create($input);

        Flash::success('Daily Stock Item saved successfully.');

        return redirect(route('dailyStockItems.index'));
    }

    /**
     * Display the specified daily_stock_item.
     *
     * @param int $id
     *
     * @return Response
     */
    public function show($id)
    {
        $dailyStockItem = $this->dailyStockItemRepository->find($id);

        if (empty($dailyStockItem)) {
            Flash::error('Daily Stock Item not found');

            return redirect(route('dailyStockItems.index'));
        }

        return view('daily_stock_items.show')->with('dailyStockItem', $dailyStockItem);
    }

    /**
     * Show the form for editing the specified daily_stock_item.
     *
     * @param int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        $dailyStockItem = $this->dailyStockItemRepository->find($id);

        if (empty($dailyStockItem)) {
            Flash::error('Daily Stock Item not found');

            return redirect(route('dailyStockItems.index'));
        }

        return view('daily_stock_items.edit')->with('dailyStockItem', $dailyStockItem);
    }

    /**
     * Update the specified daily_stock_item in storage.
     *
     * @param int $id
     * @param Updatedaily_stock_itemRequest $request
     *
     * @return Response
     */
    public function update($id, Updatedaily_stock_itemRequest $request)
    {
        $dailyStockItem = $this->dailyStockItemRepository->find($id);
        $dailyStockId = $dailyStockItem->daily_stock_id;

        if (empty($dailyStockItem)) {
            Flash::error('Daily Stock Item not found');

            return redirect(route('dailyStockItems.index'));
        }

        $dailyStockItem = $this->dailyStockItemRepository->update($request->all(), $id);

        Flash::success('Daily Stock Item updated successfully.');

        return redirect()->route('daily-stocks.show', [$dailyStockId]);
    }

    /**
     * Remove the specified daily_stock_item from storage.
     *
     * @param int $id
     *
     * @throws \Exception
     *
     * @return Response
     */
    public function destroy($id)
    {
        $dailyStockItem = $this->dailyStockItemRepository->find($id);
        $dailyStockId = $dailyStockItem->daily_stock_id;

        if (empty($dailyStockItem)) {
            Flash::error('Daily Stock Item not found');

            return redirect(route('dailyStockItems.index'));
        }

        $this->dailyStockItemRepository->delete($id);

        Flash::success('Daily Stock Item deleted successfully.');

        return redirect()->route('daily-stocks.show', [$dailyStockId]);
    }

    public function import_excel(Request $request) {
		// validasi
		$this->validate($request, [
			'file' => 'required|mimes:csv,xls,xlsx',
            'daily_stock_id' => 'required',
        ]);
 
		// menangkap file excel
		$file = $request->file('file');
        $input = $request->all();
 
		// membuat nama file unik
		$nama_file = rand().$file->getClientOriginalName();
 
        // upload ke folder file_siswa di dalam folder public
        $destination = public_path().'/file_tipe/';
		$file->move($destination, $nama_file);
        
		// import data
		Excel::import(new StockImport($input['daily_stock_id']), public_path('/file_tipe/'.$nama_file));
 
		// notifikasi dengan session
        Flash::success('Stok Berhasil Di Import berhasil diimport!');
 
		// alihkan halaman kembali
        return redirect()->route('daily-stocks.show', [$input['daily_stock_id']]);
	}


}

resources/views/daily_stock_items/create.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Daily Stock Item
        </h1>
    </section>
    <div class="content">
        @include('adminlte-templates::common.errors')
        <div class="box box-primary">
            <div class="box-body">
                <div class="row">
                    {!! Form::open(['route' => 'dailyStockItems.store']) !!}

                        @include('daily_stock_items.fields')

                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/daily_stock_items/edit.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Daily Stock Item
        </h1>
   </section>
   <div class="content">
       @include('adminlte-templates::common.errors')
       <div class="box box-primary">
           <div class="box-body">
               <div class="row">
                   {!! Form::model($dailyStockItem, ['route' => ['dailyStockItems.update', $dailyStockItem->id], 'method' => 'patch']) !!}

                        @include('daily_stock_items.fields')

                   {!! Form::close() !!}
               </div>
           </div>
       </div>
   </div>
@endsection

resources/views/daily_stock_items/fields.blade.php
<!-- Daily Stock Id Field -->
<div class="form-group col-sm-6">
    {!! Form::label('daily_stock_id', 'Daily Stock Id:') !!}
    {!! Form::number('daily_stock_id', null, ['class' => 'form-control']) !!}
</div>

<!-- Type Id Field -->
<div class="form-group col-sm-6">
    {!! Form::label('type_id', 'Type Id:') !!}
    {!! Form::number('type_id', null, ['class' => 'form-control']) !!}
</div>

<!-- Stock Field -->
<div class="form-group col-sm-6">
    {!! Form::label('stock', 'Stock:') !!}
    {!! Form::number('stock', null, ['class' => 'form-control']) !!}
</div>

<!-- Submit Field -->
<div class="form-group col-sm-12">
    {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
    <a href="{{ route('dailyStockItems.index') }}" class="btn btn-default">Cancel</a>
</div>

resources/views/daily_stock_items/index.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1 class="pull-left">Daily Stock Items</h1>
        <h1 class="pull-right">
           <a class="btn btn-primary pull-right" style="margin-top: -10px;margin-bottom: 5px" href="{{ route('dailyStockItems.create') }}">Add New</a>
        </h1>
    </section>
    <div class="content">
        <div class="clearfix"></div>

        @include('flash::message')

        <div class="clearfix"></div>
        <div class="box box-primary">
            <div class="box-body">
                    @include('daily_stock_items.table')
            </div>
        </div>
        <div class="text-center">
        
        </div>
    </div>
@endsection

resources/views/daily_stock_items/show.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Daily Stock Item
        </h1>
    </section>
    <div class="content">
        <div class="box box-primary">
            <div class="box-body">
                <div class="row" style="padding-left: 20px">
                    @include('daily_stock_items.show_fields')
                    <a href="{{ route('dailyStockItems.index') }}" class="btn btn-default">Back</a>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/daily_stock_items/show_fields.blade.php
<!-- Daily Stock Id Field -->
<div class="form-group">
    {!! Form::label('daily_stock_id', 'Daily Stock Id:') !!}
    <p>{{ $dailyStockItem->daily_stock_id }}</p>
</div>

<!-- Type Id Field -->
<div class="form-group">
    {!! Form::label('type_id', 'Type Id:') !!}
    <p>{{ $dailyStockItem->type_id }}</p>
</div>

<!-- Stock Field -->
<div class="form-group">
    {!! Form::label('stock', 'Stock:') !!}
    <p>{{ $dailyStockItem->stock }}</p>
</div>

<!-- Created At Field -->
<div class="form-group">
    {!! Form::label('created_at', 'Created At:') !!}
    <p>{{ $dailyStockItem->created_at }}</p>
</div>

<!-- Updated At Field -->
<div class="form-group">
    {!! Form::label('updated_at', 'Updated At:') !!}
    <p>{{ $dailyStockItem->updated_at }}</p>
</div>

resources/views/daily_stock_items/table.blade.php
<div class="table-responsive">
    <table class="table" id="dailyStockItems-table">
        <thead>
            <tr>
                <th>Daily Stock Id</th>
        <th>Type Id</th>
        <th>Stock</th>
                <th colspan="3">Action</th>
            </tr>
        </thead>
        <tbody>
        @foreach($dailyStockItems as $dailyStockItem)
            <tr>
                <td>{{ $dailyStockItem->daily_stock_id }}</td>
            <td>{{ $dailyStockItem->type_id }}</td>
            <td>{{ $dailyStockItem->stock }}</td>
                <td>
                    {!! Form::open(['route' => ['dailyStockItems.destroy', $dailyStockItem->id], 'method' => 'delete']) !!}
                    <div class='btn-group'>
                        <!-- <a href="{{ route('dailyStockItems.show', [$dailyStockItem->id]) }}" class='btn btn-info btn-xs table-button'><i class="fa fa-eye"></i></a> -->
                        <a href="{{ route('dailyStockItems.edit', [$dailyStockItem->id]) }}" class='btn btn-info btn-xs table-button'><i class="fa fa-pencil" aria-hidden="true"></i></a>
                        {!! Form::button('<i class="fa fa-times" aria-hidden="true"></i>', ['type' => 'submit', 'class' => 'btn btn-warning btn-xs table-button', 'onclick' => "return confirm('Apakah anda yakin?')"]) !!}
                    </div>
                    {!! Form::close() !!}
                </td>
            </tr>
        @endforeach
        </tbody>
    </table>
</div>