routes/web.php
<?php

Auth::routes([
    'register' => false, // Registration Routes...
    'reset' => false, // Password Reset Routes...
    'verify' => false, // Email Verification Routes...
]);


Route::get('/', 'HomeController@index'); 

// bisa di arahakan ke front end sebenarnya
// Route::get('/', function () {
//     return view('home');
// });
    
Route::group(['middleware' => 'auth'], function(){
    Route::get('/mesin/cari', 'mesinController@search');
    Route::resource('mesin', 'mesinController');
    Route::post('/tipe/import_excel', 'tipeController@import_excel')->name('tipe.import_excel');
    Route::get('/tipe/cari', 'tipeController@search');
    Route::post('/tipe/hapus-semua', 'tipeController@hapusSemua')->name('tipe.hapusSemua'); 
    Route::resource('tipe', 'tipeController');
    Route::get('/jadwal-mesin/grup', 'jadwal_mesinController@grup');
    Route::get('/jadwal-mesin/cari-tanggal', 'jadwal_mesinController@cariTanggal');
    Route::resource('jadwal-mesin', 'jadwal_mesinController');
    Route::get('/rencana-produksi-live', 'rencana_produksiController@live')->name('rencana-produksi.live'); 
    Route::get('/rencana-produksi-live-export', 'rencana_produksiController@live_export')->name('rencana-produksi.live-export'); 
    Route::get('/rencana-produksi-live-info', 'rencana_produksiController@live_info')->name('rencana-produksi.live-info'); 
    Route::get('/rencana-produksi/cetak-laporan', 'rencana_produksiController@cetak')->name('cetak-laporan'); 
    Route::get('/rencana-produksi/export-csv', 'rencana_produksiController@exportcsv')->name('export-csv'); 
    Route::get('/rencana-produksi/cetak-spk/{id}', 'rencana_produksiController@cetak_spk')->name('rencana-produksi.cetak_spk'); 
    Route::post('/rencana-produksi/updatestatus/{id}', 'rencana_produksiController@updateStatus')->name('update_status');
    Route::get('/rencana-produksi/generate-next/{id}', 'rencana_produksiController@generateNext')->name('rencana-produksi.generateNext'); 
    Route::post('/rencana-produksi/upload', 'rencana_produksiController@upload')->name('rencana-produksi.upload');
    Route::post('/rencana-produksi/deleteattachment/{id}', 'rencana_produksiController@deleteattachment')->name('rencana-produksi.deleteattachment');
    Route::post('/rencana-produksi/addnote', 'rencana_produksiController@addnote')->name('rencana-produksi.addnote');
   
    Route::get('/rencana-produksi/{id}/edit-ng', 'rencana_produksiController@editNG')->name('rencana-produksi.edit_ng');
    Route::post('/rencana-produksi/update-ng/{id}', 'rencana_produksiController@updateNG')->name('rencana-produksi.update_ng');
    Route::get('/rencana-produksi/backup-button}', 'rencana_produksiController@backupButton')->name('rencana-produksi.backup_button');
    Route::post('/rencana-produksi/backup-button-post', 'rencana_produksiController@backupButtonPost')->name('rencana-produksi.bakcup_button_post');

    Route::post('/jadwal/hapus-semua', 'istirahatMesinController@hapusSemua')->name('jadwal-istirahat.hapusSemua'); 
    Route::post('/jadwal-istirahat/import_excel', 'istirahatMesinController@import_excel')->name('jadwal-istirahat.import_excel'); 
    Route::post('/jadwal-istirahat/generate', 'istirahatMesinController@generate')->name('jadwal-istirahat.generate'); 
    Route::resource('jadwal-istirahat', 'istirahatMesinController');
    Route::resource('rencana-produksi', 'rencana_produksiController');
    Route::resource('draft-rencana-produksi', 'rencana_produksiControllerDraft');
    Route::resource('perubahan-rencana-produksi', 'rencana_produksiControllerCache');
    Route::get('/laporan/cetak-laporan-injection', 'laporanController@cetak')->name('cetaklaporaninjection'); 
    Route::resource('laporan', 'laporanController');
    Route::resource('shifts', 'shiftController'); 
    Route::post('/shifts/upload-attachment', 'shiftController@upload')->name('shift.upload-attachment');
    Route::post('/shifts/delete-attachment/{id}', 'shiftController@deleteattachment')->name('shifts.delete-attachment');

    Route::resource('users', 'UserController')->middleware('auth');
    Route::resource('shiftSettings', 'shift_settingController');
    Route::resource('infos', 'infoController');
    Route::resource('listShifts', 'list_shiftController');

    Route::post('/outstandings/updatestatus/{id}', 'outstandingController@updateStatus')->name('outstandings.update_status');
    Route::post('/outstandings/import_excel', 'outstandingController@import_excel')->name('outstandings.import_excel');
    Route::resource('outstandings', 'outstandingController');

    Route::post('/outstandingItems/import_excel', 'outstanding_itemController@import_excel')->name('outstandingItems.import_excel');
    Route::resource('outstandingItems', 'outstanding_itemController');
    
    Route::post('/ppics/close-ppic', 'ppicController@close_ppic')->name('ppicController.close_ppic');
    Route::resource('ppics', 'ppicController');
    Route::resource('ppicLogs', 'ppic_logController');
    Route::resource('ppicComments', 'ppic_commentController');
    Route::resource('report-daily-stock', 'report_daily_stockController');

    Route::post('/daily-stocks/updatestatus/{id}', 'daily_stockController@updateStatus')->name('daily-stocks.update_status');
    Route::resource('daily-stocks', 'daily_stockController');

    Route::get('/notifications/updatestatus/{id}', 'notificationController@updateStatus')->name('notifications.update_status');
    Route::resource('notifications', 'notificationController');
    
    Route::post('/daily-stock-item/import_excel', 'daily_stock_itemController@import_excel')->name('daily-stock-item.import_excel');
    Route::resource('dailyStockItems', 'daily_stock_itemController');

    Route::get('/laporan/cetak-laporan-injection', 'laporanController@cetak')->name('cetaklaporaninjection'); 
    Route::resource('attachments', 'attachmentsController');

});

Route::group(['middleware' => 'App\Http\Middleware\SuperVisorMiddleWare'], function(){
    Route::resource('users', 'UserController')->middleware('auth');
});

?>

app/Models/list_shift.php
<?php

namespace App\Models;

use Eloquent as Model;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * Class list_shift
 * @package App\Models
 * @version September 25, 2021, 8:40 am WIB
 *
 * @property integer shift
 * @property string mulai
 * @property string selesai
 * @property string cross_day
 */
class list_shift extends Model
{
    use SoftDeletes;

    public $table = 'list_shifts';
    

    protected $dates = ['deleted_at'];



    public $fillable = [
        'shift',
        'mulai',
        'selesai',
        'cross_day',
        'shift_category'
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'id' => 'integer',
        'shift' => 'integer',
        'mulai' => 'string',
        'selesai' => 'string',
        'cross_day' => 'string',
        'shift_category' => 'string'
    ];

    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = [
        
    ];

    
}

app/Http/Controllers/list_shiftController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\Createlist_shiftRequest;
use App\Http\Requests\Updatelist_shiftRequest;
use App\Repositories\list_shiftRepository;
use App\Http\Controllers\AppBaseController;
use Illuminate\Http\Request;
use Flash;
use Response;

class list_shiftController extends AppBaseController
{
    /** @var  list_shiftRepository */
    private $listShiftRepository;

    public function __construct(list_shiftRepository $listShiftRepo)
    {
        $this->listShiftRepository = $listShiftRepo;
    }

    /**
     * Display a listing of the list_shift.
     *
     * @param Request $request
     *
     * @return Response
     */
    public function index(Request $request)
    {
        $listShifts = $this->listShiftRepository->all();

        return view('list_shifts.index')
            ->with('listShifts', $listShifts);
    }

    /**
     * Show the form for creating a new list_shift.
     *
     * @return Response
     */
    public function create()
    {
        return view('list_shifts.create');
    }

    /**
     * Store a newly created list_shift in storage.
     *
     * @param Createlist_shiftRequest $request
     *
     * @return Response
     */
    public function store(Createlist_shiftRequest $request)
    {
        $input = $request->all();

        $listShift = $this->listShiftRepository->create($input);

        Flash::success('List Shift saved successfully.');

        return redirect(route('listShifts.index'));
    }

    /**
     * Display the specified list_shift.
     *
     * @param int $id
     *
     * @return Response
     */
    public function show($id)
    {
        $listShift = $this->listShiftRepository->find($id);

        if (empty($listShift)) {
            Flash::error('List Shift not found');

            return redirect(route('listShifts.index'));
        }

        return view('list_shifts.show')->with('listShift', $listShift);
    }

    /**
     * Show the form for editing the specified list_shift.
     *
     * @param int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        $listShift = $this->listShiftRepository->find($id);

        if (empty($listShift)) {
            Flash::error('List Shift not found');

            return redirect(route('listShifts.index'));
        }

        return view('list_shifts.edit')->with('listShift', $listShift);
    }

    /**
     * Update the specified list_shift in storage.
     *
     * @param int $id
     * @param Updatelist_shiftRequest $request
     *
     * @return Response
     */
    public function update($id, Updatelist_shiftRequest $request)
    {
        $listShift = $this->listShiftRepository->find($id);

        if (empty($listShift)) {
            Flash::error('List Shift not found');

            return redirect(route('listShifts.index'));
        }

        $listShift = $this->listShiftRepository->update($request->all(), $id);

        Flash::success('List Shift updated successfully.');

        return redirect(route('listShifts.index'));
    }

    /**
     * Remove the specified list_shift from storage.
     *
     * @param int $id
     *
     * @throws \Exception
     *
     * @return Response
     */
    public function destroy($id)
    {
        $listShift = $this->listShiftRepository->find($id);

        if (empty($listShift)) {
            Flash::error('List Shift not found');

            return redirect(route('listShifts.index'));
        }

        $this->listShiftRepository->delete($id);

        Flash::success('List Shift deleted successfully.');

        return redirect(route('listShifts.index'));
    }
}

resources/views/list_shifts/create.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            List Shift
        </h1>
    </section>
    <div class="content">
        @include('adminlte-templates::common.errors')
        <div class="box box-primary">
            <div class="box-body">
                <div class="row">
                    {!! Form::open(['route' => 'listShifts.store']) !!}

                        @include('list_shifts.fields')

                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/list_shifts/edit.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            List Shift
        </h1>
   </section>
   <div class="content">
       @include('adminlte-templates::common.errors')
       <div class="box box-primary">
           <div class="box-body">
               <div class="row">
                   {!! Form::model($listShift, ['route' => ['listShifts.update', $listShift->id], 'method' => 'patch']) !!}

                        @include('list_shifts.fields')

                   {!! Form::close() !!}
               </div>
           </div>
       </div>
   </div>
@endsection

resources/views/list_shifts/fields.blade.php
<!-- Shift Field -->
<div class="form-group col-sm-6">
    {!! Form::label('shift', 'Shift:') !!}
    {!! Form::number('shift', null, ['class' => 'form-control']) !!}
</div>

<!-- Mulai Field -->
<div class="form-group col-sm-6">
    {!! Form::label('mulai', 'Mulai:') !!}
    {!! Form::text('mulai', null, ['class' => 'form-control']) !!}
</div>

<!-- Selesai Field -->
<div class="form-group col-sm-6">
    {!! Form::label('selesai', 'Selesai:') !!}
    {!! Form::text('selesai', null, ['class' => 'form-control']) !!}
</div>

<!-- Cross Day Field -->
<div class="form-group col-sm-6">
    {!! Form::label('cross_day', 'Lewati Hari:') !!}
    {!! Form::select('cross_day', ['N' => 'N', 'Y' => 'Y'], null, ['class' => 'form-control']) !!}
</div>

<div class="form-group col-sm-6">
    {!! Form::label('shift_category', 'Kategori Shift:') !!}
    {!! Form::select('shift_category', ['1' => '1', '2' => '2', '3' => '3'], null, ['class' => 'form-control']) !!}
</div>

<!-- Submit Field -->
<div class="form-group col-sm-12">
    {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
    <a href="{{ route('listShifts.index') }}" class="btn btn-default">Cancel</a>
</div>

resources/views/list_shifts/index.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1 class="pull-left">List Shifts</h1>
        <h1 class="pull-right">
           <a class="btn btn-primary pull-right" style="margin-top: -10px;margin-bottom: 5px" href="{{ route('listShifts.create') }}">Add New</a>
        </h1>
    </section>
    <div class="content">
        <div class="clearfix"></div>

        @include('flash::message')

        <div class="clearfix"></div>
        <div class="box box-primary">
            <div class="box-body">
                    @include('list_shifts.table')
            </div>
        </div>
        <div class="text-center">
        
        </div>
    </div>
@endsection

resources/views/list_shifts/show.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            List Shift
        </h1>
    </section>
    <div class="content">
        <div class="box box-primary">
            <div class="box-body">
                <div class="row" style="padding-left: 20px">
                    @include('list_shifts.show_fields')
                    <a href="{{ route('listShifts.index') }}" class="btn btn-default">Back</a>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/list_shifts/show_fields.blade.php
<!-- Shift Field -->
<div class="form-group">
    {!! Form::label('shift', 'Shift:') !!}
    <p>{{ $listShift->shift }}</p>
</div>

<!-- Mulai Field -->
<div class="form-group">
    {!! Form::label('mulai', 'Mulai:') !!}
    <p>{{ $listShift->mulai }}</p>
</div>

<!-- Selesai Field -->
<div class="form-group">
    {!! Form::label('selesai', 'Selesai:') !!}
    <p>{{ $listShift->selesai }}</p>
</div>

<!-- Cross Day Field -->
<div class="form-group">
    {!! Form::label('cross_day', 'Cross Day:') !!}
    <p>{{ $listShift->cross_day }}</p>
</div>

<!-- Created At Field -->
<div class="form-group">
    {!! Form::label('created_at', 'Created At:') !!}
    <p>{{ $listShift->created_at }}</p>
</div>

<!-- Updated At Field -->
<div class="form-group">
    {!! Form::label('updated_at', 'Updated At:') !!}
    <p>{{ $listShift->updated_at }}</p>
</div>

resources/views/list_shifts/table.blade.php
<div class="table-responsive">
    <table class="table" id="listShifts-table">
        <thead>
            <tr>
                <th>Shift</th>
                <th>Kategori Shfit</th>
        <th>Mulai</th>
        <th>Selesai</th>
        <th>Cross Day</th>
                <th colspan="3">Action</th>
            </tr>
        </thead>
        <tbody>
        @foreach($listShifts as $listShift)
            <tr>
                <td>{{ $listShift->shift }}</td>
                <td>{{ $listShift->shift_category }}</td>
            <td>{{ $listShift->mulai }}</td>
            <td>{{ $listShift->selesai }}</td>
            <td>{{ $listShift->cross_day }}</td>
                <td>
                    {!! Form::open(['route' => ['listShifts.destroy', $listShift->id], 'method' => 'delete']) !!}
                    <div class='btn-group'>
                        <a href="{{ route('listShifts.show', [$listShift->id]) }}" class='btn btn-info btn-xs table-button'><i class="fa fa-eye"></i></a>
                        <a href="{{ route('listShifts.edit', [$listShift->id]) }}" class='btn btn-info btn-xs table-button'><i class="fa fa-pencil" aria-hidden="true"></i></a>
                        {!! Form::button('<i class="fa fa-times" aria-hidden="true"></i>', ['type' => 'submit', 'class' => 'btn btn-warning btn-xs table-button', 'onclick' => "return confirm('Apakah anda yakin?')"]) !!}
                    </div>
                    {!! Form::close() !!}
                </td>
            </tr>
        @endforeach
        </tbody>
    </table>
</div>