routes/web.php
<?php

Auth::routes([
    'register' => false, // Registration Routes...
    'reset' => false, // Password Reset Routes...
    'verify' => false, // Email Verification Routes...
]);


Route::get('/', 'HomeController@index'); 

// bisa di arahakan ke front end sebenarnya
// Route::get('/', function () {
//     return view('home');
// });
    
Route::group(['middleware' => 'auth'], function(){
    Route::get('/mesin/cari', 'mesinController@search');
    Route::resource('mesin', 'mesinController');
    Route::post('/tipe/import_excel', 'tipeController@import_excel')->name('tipe.import_excel');
    Route::get('/tipe/cari', 'tipeController@search');
    Route::post('/tipe/hapus-semua', 'tipeController@hapusSemua')->name('tipe.hapusSemua'); 
    Route::resource('tipe', 'tipeController');
    Route::get('/jadwal-mesin/grup', 'jadwal_mesinController@grup');
    Route::get('/jadwal-mesin/cari-tanggal', 'jadwal_mesinController@cariTanggal');
    Route::resource('jadwal-mesin', 'jadwal_mesinController');
    Route::get('/rencana-produksi-live', 'rencana_produksiController@live')->name('rencana-produksi.live'); 
    Route::get('/rencana-produksi-live-export', 'rencana_produksiController@live_export')->name('rencana-produksi.live-export'); 
    Route::get('/rencana-produksi-live-info', 'rencana_produksiController@live_info')->name('rencana-produksi.live-info'); 
    Route::get('/rencana-produksi/cetak-laporan', 'rencana_produksiController@cetak')->name('cetak-laporan'); 
    Route::get('/rencana-produksi/export-csv', 'rencana_produksiController@exportcsv')->name('export-csv'); 
    Route::get('/rencana-produksi/cetak-spk/{id}', 'rencana_produksiController@cetak_spk')->name('rencana-produksi.cetak_spk'); 
    Route::post('/rencana-produksi/updatestatus/{id}', 'rencana_produksiController@updateStatus')->name('update_status');
    Route::get('/rencana-produksi/generate-next/{id}', 'rencana_produksiController@generateNext')->name('rencana-produksi.generateNext'); 
    Route::post('/rencana-produksi/upload', 'rencana_produksiController@upload')->name('rencana-produksi.upload');
    Route::post('/rencana-produksi/deleteattachment/{id}', 'rencana_produksiController@deleteattachment')->name('rencana-produksi.deleteattachment');
    Route::post('/rencana-produksi/addnote', 'rencana_produksiController@addnote')->name('rencana-produksi.addnote');
   
    Route::get('/rencana-produksi/{id}/edit-ng', 'rencana_produksiController@editNG')->name('rencana-produksi.edit_ng');
    Route::post('/rencana-produksi/update-ng/{id}', 'rencana_produksiController@updateNG')->name('rencana-produksi.update_ng');
    Route::get('/rencana-produksi/backup-button}', 'rencana_produksiController@backupButton')->name('rencana-produksi.backup_button');
    Route::post('/rencana-produksi/backup-button-post', 'rencana_produksiController@backupButtonPost')->name('rencana-produksi.bakcup_button_post');

    Route::post('/jadwal/hapus-semua', 'istirahatMesinController@hapusSemua')->name('jadwal-istirahat.hapusSemua'); 
    Route::post('/jadwal-istirahat/import_excel', 'istirahatMesinController@import_excel')->name('jadwal-istirahat.import_excel'); 
    Route::post('/jadwal-istirahat/generate', 'istirahatMesinController@generate')->name('jadwal-istirahat.generate'); 
    Route::resource('jadwal-istirahat', 'istirahatMesinController');
    Route::resource('rencana-produksi', 'rencana_produksiController');
    Route::resource('draft-rencana-produksi', 'rencana_produksiControllerDraft');
    Route::resource('perubahan-rencana-produksi', 'rencana_produksiControllerCache');
    Route::get('/laporan/cetak-laporan-injection', 'laporanController@cetak')->name('cetaklaporaninjection'); 
    Route::resource('laporan', 'laporanController');
    Route::resource('shifts', 'shiftController'); 
    Route::post('/shifts/upload-attachment', 'shiftController@upload')->name('shift.upload-attachment');
    Route::post('/shifts/delete-attachment/{id}', 'shiftController@deleteattachment')->name('shifts.delete-attachment');

    Route::resource('users', 'UserController')->middleware('auth');
    Route::resource('shiftSettings', 'shift_settingController');
    Route::resource('infos', 'infoController');
    Route::resource('listShifts', 'list_shiftController');

    Route::post('/outstandings/updatestatus/{id}', 'outstandingController@updateStatus')->name('outstandings.update_status');
    Route::post('/outstandings/import_excel', 'outstandingController@import_excel')->name('outstandings.import_excel');
    Route::resource('outstandings', 'outstandingController');

    Route::post('/outstandingItems/import_excel', 'outstanding_itemController@import_excel')->name('outstandingItems.import_excel');
    Route::resource('outstandingItems', 'outstanding_itemController');
    
    Route::post('/ppics/close-ppic', 'ppicController@close_ppic')->name('ppicController.close_ppic');
    Route::resource('ppics', 'ppicController');
    Route::resource('ppicLogs', 'ppic_logController');
    Route::resource('ppicComments', 'ppic_commentController');
    Route::resource('report-daily-stock', 'report_daily_stockController');

    Route::post('/daily-stocks/updatestatus/{id}', 'daily_stockController@updateStatus')->name('daily-stocks.update_status');
    Route::resource('daily-stocks', 'daily_stockController');

    Route::get('/notifications/updatestatus/{id}', 'notificationController@updateStatus')->name('notifications.update_status');
    Route::resource('notifications', 'notificationController');
    
    Route::post('/daily-stock-item/import_excel', 'daily_stock_itemController@import_excel')->name('daily-stock-item.import_excel');
    Route::resource('dailyStockItems', 'daily_stock_itemController');

    Route::get('/laporan/cetak-laporan-injection', 'laporanController@cetak')->name('cetaklaporaninjection'); 
    Route::resource('attachments', 'attachmentsController');

});

Route::group(['middleware' => 'App\Http\Middleware\SuperVisorMiddleWare'], function(){
    Route::resource('users', 'UserController')->middleware('auth');
});

?>

resources/views/rencana_proudksis_draft/create.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Rencana Produksi
        </h1>
    </section>
    <div class="content">
        @include('adminlte-templates::common.errors')
        <div class="box box-primary">
            <div class="box-body">
                <div class="row">
                    {!! Form::open(['route' => 'draft-rencana-produksi.store']) !!}

                        @include('rencana_proudksis_draft.fields')

                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/rencana_proudksis_draft/edit.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Rencana Produksi
        </h1>
   </section>
   <div class="content">
       @include('adminlte-templates::common.errors')
       <div class="box box-primary">
           <div class="box-body">
               <div class="row">
                   {!! Form::model($rencProd, 
                    ['route' => ['draft-rencana-produksi.update', $rencProd->id], 'method' => 'patch']) !!}
                        @include('rencana_proudksis_draft.fields')
                   {!! Form::close() !!}
               </div>
           </div>
       </div>
   </div>
@endsection

resources/views/rencana_proudksis_draft/edit_ng.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Rencana Produksi
        </h1>
   </section>
   <div class="content">
       @include('adminlte-templates::common.errors')
       <div class="box box-primary">
           <div class="box-body">
               <div class="row">
                   {!! Form::model($rencProd, ['route' => ['rencana-produksi.update_ng', $rencProd->id], 'method' => 'post']) !!}
                        @include('rencana_proudksis_draft.edit_ng_fields')
                   {!! Form::close() !!}
               </div>
           </div>
       </div>
   </div>
@endsection

resources/views/rencana_proudksis_draft/edit_ng_fields.blade.php
<div class="col-sm-12" style="margin-bottom:30px">
    <div class="form-group col-sm-12 border-box-middle"> OPERATOR & NG SETTINGS</div>
    
    <div class="form-group col-sm-6">
        {!! Form::label('operator', 'Operator:') !!}
        {!! Form::text('operator', null, ['class' => 'form-control',  'id'=>'operator', 
            'readonly' => (isset($rencProd) and $rencProd->status == 'aktual') ? false : true ]) !!}
    </div>

    <div class="form-group col-sm-6">
        {!! Form::label('berat_ng_produksi', 'NG proses: Berat NG produksi (Gr):') !!}
        {!! Form::text('berat_ng_produksi', null, ['class' => 'form-control',  'id'=>'berat_ng_produksi',
            'readonly' => (isset($rencProd) and $rencProd->status == 'aktual') ? false : true]) !!}
    </div>

    <div class="form-group col-sm-6">
        {!! Form::label('berat_ng_produksi', 'NG setting: Berat Set Awal (Gr):') !!}
        {!! Form::text('berat_set_awal', null, ['class' => 'form-control',  'id'=>'berat_set_awal',
            'readonly' => (isset($rencProd) and $rencProd->status == 'aktual') ? false : true]) !!}
    </div>

    <div class="form-group col-sm-6">
        {!! Form::label('target_settings', 'Target Setting:') !!}
        {!! Form::text('target_settings', null, ['class' => 'form-control',  'id'=>'target_settings',
            'readonly' => (isset($rencProd) and $rencProd->status == 'aktual') ? false : true]) !!}
    </div>
</div>

<div class="form-group col-sm-12">
    {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
    <a href="{{ route('rencana-produksi.index') }}" class="btn btn-info">Cancel</a>
</div>

resources/views/rencana_proudksis_draft/fields.blade.php
<div class="col-sm-12" style="margin-bottom:30px">
    <div class="form-group col-sm-6">
        {!! Form::label('type_id', 'ID Tipe & Nama Tipe:') !!}
        {!! Form::text('', null, ['class' => 'form-control', 'id'=>'search_type',
            'readonly' => (isset($rencProd) and $rencProd->status == 'aktual') ? true : false]) !!}
        <div style="display: flex; flex-direction: row">
        {!! Form::text('type_id', (isset($rencProd)) ? $rencProd->type_id : null, ['class' => 'form-control','id'=>'type_id', 'readonly' => 'true', 'placeholder' => 'ID']) !!}
        {!! Form::text('nama', (isset($rencProd)) ? $rencProd->nama : null, ['class' => 'form-control','id'=>'type_name', 'readonly' => 'true', 'placeholder' => 'Tipe']) !!}
        </div>
    </div>

    <div class="form-group col-sm-4">
        {!! Form::label('jumlah_rencana_produksi', 'Jumlah Rencana Produksi:') !!}
        {!! Form::number('jumlah_rencana_produksi', null, [
            'class' => 'form-control', 'id'=>'rencana_produksi', 'onchange' => 'calculateEstimasi()',
            'readonly' => (isset($rencProd) and $rencProd->status == 'aktual') ? true : false]) !!}
    </div>

    <div class="form-group col-sm-2">
        {!! Form::label('stauan', 'Satuan:') !!}
        {!! Form::select('satuan', [
            'pcs' => 'PCS', 
            'set' => 'SET', 
        ], null, ['class' => 'form-control']) !!}
    </div>

    <div class="form-group col-sm-8">
        {!! Form::label('mesin_id', 'Mesin:') !!}
        {!! Form::text('null', (isset($rencProd)) ? $rencProd->mesin->nama : null, [
            'class' => 'form-control', 
            'id'=>'search_mesin',
            'readonly' => (isset($rencProd) and $rencProd->status == 'aktual') ? true : false]) !!}
        {!! Form::hidden('mesin_id', (isset($rencProd)) ? $rencProd->mesin_id : null, ['class' => 'form-control','id'=>'mesin_id']) !!}
        {!! Form::hidden('shift_category', (isset($rencProd)) ? $rencProd->shift_category : null, ['class' => 'form-control','id'=>'shift_category']) !!}
    </div>
    <div class="form-group col-sm-4">
        {!! Form::label('mesin_id', 'Urutan Booking:') !!}
        {!! Form::text('urutan_booking',  null, 
            [
                'class' => 'form-control', 
                'id'=>'urutan_booking',
                'readonly' => !isset($rencProd) ? true : false
            ] )
        !!}
    </div>

    <!-- @if( !empty($rencProd)) -->
    <!-- <div class="form-group col-sm-6">
        {!! Form::label('jumlah_aktual_produksi', 'Jumlah Aktual Produksi:') !!}
        {!! Form::number('jumlah_aktual_produksi', null, ['class' => 'form-control', 'readonly' => 'true']) !!}
    </div> -->
    <!-- @endif -->
    


</div>


<div class="col-sm-12" style="margin-bottom:30px">
    <div class="form-group col-sm-12 border-box-middle"> ESTIMASI </div>
    <div class="form-group col-sm-6">
        {!! Form::label('estimasi_durasi', 'Estimasi Durasi (Hari Jam:Menit):') !!}
        {!! Form::text('estimasi_durasi_display', null, ['class' => 'form-control', 'readonly'=>'true', 'id'=>'estimasi_durasi_display']) !!}
        {!! Form::hidden('estimasi_durasi', (isset($rencProd)) ? $rencProd->estimasi_durasi : null, ['class' => 'form-control', 'readonly'=>'true', 'id'=>'estimasi_durasi']) !!}
    </div>

    <div class="form-group col-sm-6">
        {!! Form::label('estimasi_total_shift', 'Estimasi Total Shift:') !!}
        {!! Form::text('estimasi_total_shift', null, ['class' => 'form-control', 'readonly'=>'true', 'id'=>'estimasi_total_shift']) !!}
    </div>


    <!-- Estimasi Total Shift Field -->
    <!-- <div class="form-group col-sm-6">
        {!! Form::label('persentasi_cycle_time', 'Persentasi Cycle Time:') !!}
        {!! Form::text('persentasi_cycle_time', null, ['class' => 'form-control', 'readonly'=>'true']) !!}
    </div> -->

    <div class="form-group col-sm-12 border-box-middle"> DETAIL TIPE </div>
    <div class="form-group col-sm-6">
        {!! Form::label('cycle_time', 'Cycle Time / Menit: ') !!}
        {!! Form::text('cycle_time', null, ['class' => 'form-control', 'id'=>'cycle_time', 'readonly'=>'true']) !!}
    </div>

    <!-- Jumlah Operator Field -->
    <div class="form-group col-sm-6">
        {!! Form::label('jumlah_operator', 'Jumlah Operator:') !!}
        {!! Form::text('jumlah_operator', null, ['class' => 'form-control', 'readonly'=>'true', 'id'=>'jumlah_operator']) !!}
    </div>

    <!-- Toleransi Field -->
    <div class="form-group col-sm-6">
        {!! Form::label('toleransi', 'Toleransi (%):') !!}
        {!! Form::number('toleransi', null, ['class' => 'form-control', 'id'=>'toleransi', 'readonly'=>'true']) !!}
    </div>
    
    <!-- Durasi Dandon Field -->
    <div class="form-group col-sm-6">
        {!! Form::label('durasi_dandon', 'Durasi Dandon  (menit): ') !!}
        {!! Form::number('durasi_dandon', null, ['class' => 'form-control', 'id'=>'durasi_dandon', 'readonly'=>'true']) !!}
    </div>

    <!-- Durasi Produksi Field -->
    <div class="form-group col-sm-6">
        {!! Form::label('durasi_produksi', 'Durasi Produksi:') !!}
        {!! Form::text('durasi_produksi', null, ['class' => 'form-control', 'readonly' => 'true', 'id'=>'durasi_produksi', 'readonly'=>'true']) !!}
    </div>

    <!-- Type Pasangan Field -->
    <div class="form-group col-sm-6">
        {!! Form::label('type_pasangan', 'Tipe Pasangan:') !!}
        {!! Form::text('type_pasangan', null, ['class' => 'form-control', 'readonly'=>'true', 'id'=>'type_pasangan']) !!}
    </div>

    <div class="form-group col-sm-6">
        {!! Form::label('berat_per_pcs', 'Berat / Pcs:') !!}
        {!! Form::text('berat_per_pcs', null, ['class' => 'form-control', 'readonly'=>'true', 'id'=>'berat_per_pcs']) !!}
    </div>

    

    <!-- Durasi Produksi Field -->
    <div class="form-group col-sm-6">
        {!! Form::label('barang_lain', 'Barang Lain:') !!}
        {!! Form::text('barang_lain', null, ['class' => 'form-control', 'readonly' => 'true', 'id'=>'barang_lain', 'readonly'=>'true']) !!}
        <p id="messageBR" style="color: red"></p>
    </div>

</div>

<!-- Submit Field -->
<div class="form-group col-sm-12">
    {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
    <a href="{{ route('rencana-produksi.index') }}" class="btn btn-info">Cancel</a>
</div>

@section('scripts')
    <script type="text/javascript">

        $('#mulai, #selesai').datetimepicker({
            format: 'YYYY-MM-DDTHH:mm',
            useCurrent: true,
            locale: 'id'
        })

        var path = "{{ url('/mesin/cari') }}";
        $input = $('#search_mesin');
        $input.typeahead({
            minLength: 0,
            items: 10,
            source:  function (query, process) {
                return $.get(path, { q: query }, function (data) {
                    return process(data);
                });
            },
            autoSelect: true,
            displayText: function(item){ return `kode:${item.kode} - ${item.nama} `;}
        });
        $input.change(function() {
            var current = $input.typeahead("getActive");
            $('input[id=mesin_id]').val(current.id);
            $('input[id=shift_category]').val(current.shift_category);
            $('input[id=kode_mesin]').val(current.kode);
            calculateTanggal()
        });

        var path2 = "{{ url('/tipe/cari') }}";
        $input2 = $('#search_type');
        $input2.typeahead({
            minLength: 0,
            items: 10,
            source:  function (query, process) {
                return $.get(path2, { q: query }, function (data) {
                    return process(data);
                });
            },
            autoSelect: true,
            displayText: function(item){ return `${item.nama} `;}
        });
    
        $input2.change(function() {
            $('input[id=type_name]').val('');
            var current = $input2.typeahead("getActive");
            $('input[class=search_type]').val(current.nama);
            $('input[id=type_name]').val(current.nama);
            $('input[id=type_id]').val(current.id);
            $('input[id=cycle_time]').val(current.cycle_time);
            $('input[id=jumlah_operator]').val(current.jumlah_operator);
            $('input[id=toleransi]').val(current.toleransi);
            $('input[id=durasi_produksi]').val(current.durasi_produksi);
            $('input[id=durasi_dandon]').val(current.durasi_dandon);
            $('input[id=type_pasangan]').val(current.type_pasangan);
            $('input[id=berat_per_pcs]').val(current.berat);
            $('input[id=barang_lain]').val(current.barang_lain);
            if (current.barang_lain) {
                document.querySelector("#messageBR").innerHTML = "Jangan lupa untuk membuat rencana produksi barang ini!!";
            } else {
                document.querySelector("#messageBR").innerHTML = "";
            }
            calculateEstimasi()
        });

        function calculateEstimasi() {
            let rencanaProduksi = $('input[id=rencana_produksi]').val();
            let cycleTime =  $('input[id=cycle_time]').val(); //60 per 60 second
            let durasiProduksi = $('input[id=durasi_produksi]').val(); // 90 second
            let durasiDandon = $('input[id=durasi_dandon]').val() * 60; // durasi dandon convert to be second
            let estimasiDurasi = rencanaProduksi / cycleTime * durasiProduksi // hasil dalam second
            estimasiDurasi = durasiDandon + estimasiDurasi
            var formatted = secondsToDhms(estimasiDurasi);
            $('input[id=estimasi_durasi_display]').val(formatted);
            $('input[id=estimasi_durasi]').val(estimasiDurasi);
            // calculate estimasi total shift
            const aShiftInSecond = 28800 //8 jam * 60 menit * 60 second
            let shiftEstimation = estimasiDurasi / aShiftInSecond;
            $('input[id=estimasi_total_shift]').val(shiftEstimation);
        }

        function secondsToDhms(seconds) {
            seconds = Number(seconds);
            var d = Math.floor(seconds / (3600*24));
            var h = Math.floor(seconds % (3600*24) / 3600);
            var m = Math.floor(seconds % 3600 / 60);
            var s = Math.floor(seconds % 60);
            return `${d} ${h}:${m}`
        }

        async function calculateTanggal() {
            let path = "{{ url('/jadwal-mesin/cari-tanggal') }}";
            let mesin_id = $('input[id=mesin_id]').val();
            let data = await $.get(path, { mesin_id: mesin_id });
            $('input[id=mulai]').val(data.mulai);
            $('input[id=shift]').val(data.shift);
        }

    </script>
@endsection

resources/views/rencana_proudksis_draft/index.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1 class="pull-left">Draft Rencana Produksi</h1>
        <h1 class="pull-right">
           <a class="btn btn-primary pull-right" 
            style="margin-top: -10px;margin-bottom: 5px" 
            href="{{ route('draft-rencana-produksi.create') }}">Tambah Data</a>
        </h1>
    </section>
    <div class="content">
        <div class="clearfix"></div>

        @include('flash::message')

        <div class="clearfix"></div>
       
        <div class="box box-primary">
            <div class="box-header">
            <h3 class="box-title"></h3>
                <div class="box-tools">
                    <form action="" method="GET" class="search-apsc">
                        <!-- {!! Form::select('status', ['aktif' => 'Aktif', 'pending'=>'Pending', 'aktual'=>'Aktual', 'cancel' => 'Cancel', 'semua' => 'Semua'], null, ['class' => 'form-control filter-input', 'id'=>'status']) !!} -->
                        <input type="text" class="form-control filter-input" placeholder="Mesin" id='mesin'>
                        <input type="hidden" name="mesin_id" class="form-control filter-input" placeholder="Mesin" id='mesin_id'>
                        <!-- <input type="date" name='tanggal' class="form-control filter-input" placeholder="Tanggal" id='tanggalfilter' > -->
                        <!-- <input type="text" name='selesai' class="form-control filter-input" placeholder="Selesai" id='tanggalfilter2' > -->
                        <div class="input-group-btn search-button-container">
                            <button type="submit" class="btn btn-info search-button" ><i class="fa fa-search"></i></button>
                            <!-- <button type="button" data-href="{{ route('cetak-laporan') }}"  class="btn btn-info search-button" id="searchButton">PRINT</i></button> -->
                            <a class="btn btn-info search-button" href="{{ route('rencana-produksi.index', ['status'=>'aktif']) }}" 
                                style="z-index: 10">Lihat Semua RP</a>
                        </div>
                    </form>
                </div>
            </div>

            <div class="box-body">
                @include('rencana_proudksis_draft.table')
            </div>

            <div class="box-footer clearfix">
                {{ $rencanaProduksisDraft->links() }}
            </div>
        </div>
    </div>
@endsection

@section('scripts')
    <script type="text/javascript">

        // $('#tanggalfilter, #tanggalfilter2').datetimepicker({
        //     format: 'DD-MM-YYYY',
        //     useCurrent: true,
        //     locale: 'id'
        // })

        var path = "{{ url('/mesin/cari') }}";
        $input = $('#mesin');
        $input.typeahead({
            minLength: 0,
            items: 10,
            source:  function (query, process) {
                return $.get(path, { q: query }, function (data) {
                    return process(data);
                });
            },
            autoSelect: true,
            displayText: function(item){ return `${item.nama} `;}
        });

        $input.change(function() {
            var current = $input.typeahead("getActive");
            $('input[id=mesin_id]').val(current.id);
        });

        $("#searchButton").click(function() {
            let status = document.getElementById("status").value
            let mesin_id = document.getElementById("mesin").value
            let date = document.getElementById("tanggalfilter").value
            let href = $(this).data("href");
            let url = href + "?tanggal=" + date + '&status=' + status + '&mesin_id=' + mesin_id 
            window.open(
                url,
                '_blank' // <- This is what makes it open in a new window.
            );
        });

        $("#searchButton2").click(function() {
            let status = document.getElementById("status").value
            let mesin_id = document.getElementById("mesin").value
            let date = document.getElementById("tanggalfilter").value
            // let selesai = document.getElementById("tanggalfilter2").value
            let href = $(this).data("href");
            let url = href + "?tanggal=" + date + '&status=' + status + '&mesin_id=' + mesin_id 
            window.open(
                url,
                '_blank' // <- This is what makes it open in a new window.
            );
        });

    </script>
@endsection

resources/views/rencana_proudksis_draft/table.blade.php
<div class="table-responsive">
    <table class="table data" id="rencanaProduksis-table">
        <thead>
            <tr>
                <th>Urutan Booking</th>
                <!-- <th>Mulai</th> -->
                <!-- <th>Selesai</th> -->
                <!-- <th>Urutan</th> -->
                <th>Mesin</th>
                <th>Tipe</th>
                <th>Status</th>
                <!-- <th>Kapasitas Produksi</th>  -->
                <th>Est. Total Durasi</th>
                <th>Jumlah Produksi</th>
                <th>Action</th>
                <!-- <th>Jumlah Aktual</th> -->
                <!-- <th>% Aktual</th> -->
                <!-- <th>% Aktual Kap. Mesin</th> -->
                <!-- <th></th> -->
            </tr>
        </thead>
        <tbody>
        @foreach($rencanaProduksisDraft as $rencanaProduksi)
            <tr>
                <td><a href="{{ route('draft-rencana-produksi.show', [$rencanaProduksi->id]) }}" class='table-link'>{{ $rencanaProduksi->urutan_booking }}</a></td>
                <!-- <td>{{ isset($rencanaProduksi->mulai) ? $rencanaProduksi->mulai->format('d/m/y H:i') : '-'}}</td> -->
                <!-- <td>{{ isset($rencanaProduksi->selesai) ? $rencanaProduksi->selesai->format('d/m/y H:i') : '-' }}</td> -->
                <!-- <td>{{ $rencanaProduksi->urutan ?? '-' }}</td> -->
                <td>{{ $rencanaProduksi->mesin ? $rencanaProduksi->mesin->nama : '-' }}</td>
                <td>{{ $rencanaProduksi->nama }}</td>  <!-- TIPE -->
                <td> {{ strtoupper($rencanaProduksi->status) }} </td>
                <!-- <td> ? </td> -->
                <td>{{ $rencanaProduksi->estimasi_durasi ?? '-' }}</td>
                <td>{{ $rencanaProduksi->jumlah_rencana_produksi ?? '-' }}</td>
                <!-- <td>{{ $rencanaProduksi->jumlah_aktual_produksi ?? '-' }}</td> -->
                <!-- <td>{{ $rencanaProduksi->persentasi_aktual ?? '-' }}</td> -->
                <!-- <td> ? </td> -->
                <td>
                    {!! Form::open(['route' => ['draft-rencana-produksi.destroy', $rencanaProduksi->id], 'method' => 'delete']) !!}
                    <div class='btn-group'>
                        <a href="{{ route('draft-rencana-produksi.edit', [$rencanaProduksi->id]) }}" class='btn btn-info btn-xs table-button'>
                            <i class="fa fa-pencil" aria-hidden="true"></i>
                        </a>
                        {!! Form::button('<i class="fa fa-times" aria-hidden="true"></i>', 
                            ['type' => 'submit', 
                            'class' => 'btn btn-warning btn-xs table-button', 
                            'onclick' => "return confirm('Apakah anda yakin?')"]) !!}
                    </div>
                    {!! Form::close() !!}
                </td>
            </tr>
        @endforeach
        </tbody>
    </table>
</div>