routes/web.php
<?php

Auth::routes([
    'register' => false, // Registration Routes...
    'reset' => false, // Password Reset Routes...
    'verify' => false, // Email Verification Routes...
]);


Route::get('/', 'HomeController@index'); 

// bisa di arahakan ke front end sebenarnya
// Route::get('/', function () {
//     return view('home');
// });
    
Route::group(['middleware' => 'auth'], function(){
    Route::get('/mesin/cari', 'mesinController@search');
    Route::resource('mesin', 'mesinController');
    Route::post('/tipe/import_excel', 'tipeController@import_excel')->name('tipe.import_excel');
    Route::get('/tipe/cari', 'tipeController@search');
    Route::post('/tipe/hapus-semua', 'tipeController@hapusSemua')->name('tipe.hapusSemua'); 
    Route::resource('tipe', 'tipeController');
    Route::get('/jadwal-mesin/grup', 'jadwal_mesinController@grup');
    Route::get('/jadwal-mesin/cari-tanggal', 'jadwal_mesinController@cariTanggal');
    Route::resource('jadwal-mesin', 'jadwal_mesinController');
    Route::get('/rencana-produksi-live', 'rencana_produksiController@live')->name('rencana-produksi.live'); 
    Route::get('/rencana-produksi-live-export', 'rencana_produksiController@live_export')->name('rencana-produksi.live-export'); 
    Route::get('/rencana-produksi-live-info', 'rencana_produksiController@live_info')->name('rencana-produksi.live-info'); 
    Route::get('/rencana-produksi/cetak-laporan', 'rencana_produksiController@cetak')->name('cetak-laporan'); 
    Route::get('/rencana-produksi/export-csv', 'rencana_produksiController@exportcsv')->name('export-csv'); 
    Route::get('/rencana-produksi/cetak-spk/{id}', 'rencana_produksiController@cetak_spk')->name('rencana-produksi.cetak_spk'); 
    Route::post('/rencana-produksi/updatestatus/{id}', 'rencana_produksiController@updateStatus')->name('update_status');
    Route::get('/rencana-produksi/generate-next/{id}', 'rencana_produksiController@generateNext')->name('rencana-produksi.generateNext'); 
    Route::post('/rencana-produksi/upload', 'rencana_produksiController@upload')->name('rencana-produksi.upload');
    Route::post('/rencana-produksi/deleteattachment/{id}', 'rencana_produksiController@deleteattachment')->name('rencana-produksi.deleteattachment');
    Route::post('/rencana-produksi/addnote', 'rencana_produksiController@addnote')->name('rencana-produksi.addnote');
   
    Route::get('/rencana-produksi/{id}/edit-ng', 'rencana_produksiController@editNG')->name('rencana-produksi.edit_ng');
    Route::post('/rencana-produksi/update-ng/{id}', 'rencana_produksiController@updateNG')->name('rencana-produksi.update_ng');
    Route::get('/rencana-produksi/backup-button}', 'rencana_produksiController@backupButton')->name('rencana-produksi.backup_button');
    Route::post('/rencana-produksi/backup-button-post', 'rencana_produksiController@backupButtonPost')->name('rencana-produksi.bakcup_button_post');

    Route::post('/jadwal/hapus-semua', 'istirahatMesinController@hapusSemua')->name('jadwal-istirahat.hapusSemua'); 
    Route::post('/jadwal-istirahat/import_excel', 'istirahatMesinController@import_excel')->name('jadwal-istirahat.import_excel'); 
    Route::post('/jadwal-istirahat/generate', 'istirahatMesinController@generate')->name('jadwal-istirahat.generate'); 
    Route::resource('jadwal-istirahat', 'istirahatMesinController');
    Route::resource('rencana-produksi', 'rencana_produksiController');
    Route::resource('draft-rencana-produksi', 'rencana_produksiControllerDraft');
    Route::resource('perubahan-rencana-produksi', 'rencana_produksiControllerCache');
    Route::get('/laporan/cetak-laporan-injection', 'laporanController@cetak')->name('cetaklaporaninjection'); 
    Route::resource('laporan', 'laporanController');
    Route::resource('shifts', 'shiftController'); 
    Route::post('/shifts/upload-attachment', 'shiftController@upload')->name('shift.upload-attachment');
    Route::post('/shifts/delete-attachment/{id}', 'shiftController@deleteattachment')->name('shifts.delete-attachment');

    Route::resource('users', 'UserController')->middleware('auth');
    Route::resource('shiftSettings', 'shift_settingController');
    Route::resource('infos', 'infoController');
    Route::resource('listShifts', 'list_shiftController');

    Route::post('/outstandings/updatestatus/{id}', 'outstandingController@updateStatus')->name('outstandings.update_status');
    Route::post('/outstandings/import_excel', 'outstandingController@import_excel')->name('outstandings.import_excel');
    Route::resource('outstandings', 'outstandingController');

    Route::post('/outstandingItems/import_excel', 'outstanding_itemController@import_excel')->name('outstandingItems.import_excel');
    Route::resource('outstandingItems', 'outstanding_itemController');
    
    Route::post('/ppics/close-ppic', 'ppicController@close_ppic')->name('ppicController.close_ppic');
    Route::resource('ppics', 'ppicController');
    Route::resource('ppicLogs', 'ppic_logController');
    Route::resource('ppicComments', 'ppic_commentController');
    Route::resource('report-daily-stock', 'report_daily_stockController');

    Route::post('/daily-stocks/updatestatus/{id}', 'daily_stockController@updateStatus')->name('daily-stocks.update_status');
    Route::resource('daily-stocks', 'daily_stockController');

    Route::get('/notifications/updatestatus/{id}', 'notificationController@updateStatus')->name('notifications.update_status');
    Route::resource('notifications', 'notificationController');
    
    Route::post('/daily-stock-item/import_excel', 'daily_stock_itemController@import_excel')->name('daily-stock-item.import_excel');
    Route::resource('dailyStockItems', 'daily_stock_itemController');

    Route::get('/laporan/cetak-laporan-injection', 'laporanController@cetak')->name('cetaklaporaninjection'); 
    Route::resource('attachments', 'attachmentsController');

});

Route::group(['middleware' => 'App\Http\Middleware\SuperVisorMiddleWare'], function(){
    Route::resource('users', 'UserController')->middleware('auth');
});

?>

app/Models/ppic.php
<?php

namespace App\Models;

use Eloquent as Model;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * Class ppic
 * @package App\Models
 * @version September 8, 2022, 11:21 pm WIB
 *
 * @property string $tanggal
 * @property integer $type_id
 * @property integer $outstanding_stok
 * @property string $status
 * @property string $tanggal_produksi
 * @property string $keterangan
 */
class ppic extends Model
{
    use SoftDeletes;

    public $table = 'ppics';
    

    protected $dates = ['deleted_at'];



    public $fillable = [
        'tanggal',
        'type_id',
        'outstanding_stok',
        'status',
        'tanggal_produksi',
        'keterangan',
        'no_transaksi',
        'notify_purchasing',
        'last_update'
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'id' => 'integer',
        'tanggal' => 'date',
        'type_id' => 'integer',
        'outstanding_stok' => 'integer',
        'status' => 'string',
        'tanggal_produksi' => 'date',
        'keterangan' => 'string',
        'no_transaksi' => 'string',
        'notify_purchasing' => 'string',
        'ppic' => 'datetime',
    ];

    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = [
        
    ];

    public function type(){
        return $this->belongsTo(\App\Models\tipe::class, 'type_id');
    }

    // public function ppic(){
    //     return $this->belongsTo(\App\Models\tipe::class, 'ppic_id');
    // }

    
}

app/Http/Controllers/ppicController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CreateppicRequest;
use App\Http\Requests\UpdateppicRequest;
use App\Http\Controllers\AppBaseController;
use App\Repositories\ppicRepository;
use App\Repositories\ppic_logRepository;
use App\Repositories\ppic_commentRepository;
use App\Repositories\report_daily_stockRepository;
use App\Repositories\notificationRepository;
use Illuminate\Http\Request;
use Flash;
use Response;
use Illuminate\Support\Facades\DB;

class ppicController extends AppBaseController
{
    /** @var  ppicRepository */
    private $ppicRepository;
    private $ppicLogRepository;
    private $ppicCommentRepository;
    private $reportDailyStockRepository;
    private $notificationRepository;

    public function __construct(
        ppicRepository $ppicRepo, 
        ppic_logRepository $ppicLogRepo,
        ppic_commentRepository $ppicCommentRepo,
        report_daily_stockRepository $reportDailyStockRepo,
        notificationRepository $notificationRepo
        )
    {
        $this->ppicRepository = $ppicRepo;
        $this->ppicLogRepository = $ppicLogRepo;
        $this->ppicCommentRepository = $ppicCommentRepo;
        $this->reportDailyStockRepository = $reportDailyStockRepo;
        $this->notificationRepository = $notificationRepo;
    }

    public function index(Request $request)
    {
        $ppics = $this->ppicRepository->all();

        return view('ppics.index')
            ->with('ppics', $ppics);
    }

    /**
     * Show the form for creating a new ppic.
     *
     * @return Response
     */
    public function create(Request $request)
    {
        $report_id = $request->get('report_id');
        $type_id = $request->get('type_id');
        $type_name = $request->get('type_name');
        $outstanding = $request->get('outstanding');
        return view('ppics.create')
            ->with('report_id',$report_id)
            ->with('type_id', $type_id)
            ->with('type_name', $type_name)
            ->with('outstanding', $outstanding);
    }

    /**
     * Store a newly created ppic in storage.
     *
     * @param CreateppicRequest $request
     *
     * @return Response
     */
    public function store(CreateppicRequest $request)
    {
        $input = $request->all();
        $input['no_transaksi'] = $this->generateNoTransaksi($input['tanggal']);
        $ppic = $this->ppicRepository->create($input);

        // update report daily stock
        $report_id = $input['report_id'];
        $this->reportDailyStockRepository->update(array('ppic_id'  => $ppic->id), $report_id);

        // notif purchasing jika PPIC failed
        dd($ppic->notify_purchasing);
        if($ppic->status == 'failed' && $ppic->notify_purchasing == 'y') {
            $input2 = array (
                'departement'=>'purchasing',
                'tanggal' => $ppic->tanggal,
                'status' => $ppic->keterangan,
                'ppic_id' => $ppic->id,
                'is_read' => 'F',
            );
            $this->notificationRepository->create($input2);
        }

        $input['ppic_id'] = $ppic->id;
        $input['user_id'] = $request->user()->id;
        $ppicLog = $this->ppicLogRepository->create($input);
        
        Flash::success('PPIC saved successfully.');
        return redirect(route('report-daily-stock.index'));
    }

    /**
     * Display the specified ppic.
     *
     * @param int $id
     *
     * @return Response
     */
    public function show($id)
    {
        $ppic = $this->ppicRepository->find($id);
        $ppicLogs = $this->ppicLogRepository->all()->where('ppic_id', $id);
        $ppicComments = $this->ppicCommentRepository->all()->where('ppic_id', $id);;

        if (empty($ppic)) {
            Flash::error('Ppic not found');
            return redirect(route('report-daily-stock.index'));
        }

        return view('ppics.show')->with('ppic', $ppic)
            ->with('ppicLogs', $ppicLogs)
            ->with('ppicComments', $ppicComments);
    }

    /**
     * Show the form for editing the specified ppic.
     *
     * @param int $id
     *
     * @return Response
     */
    public function edit(Request $request, $id)
    {
        $ppic = $this->ppicRepository->find($id);
        $report_id = $request->get('report_id');
        $type_id = $request->get('type_id');
        $outstanding = $request->get('outstanding');
        $type_name = $request->get('type_name');
  
        if (empty($ppic)) {
            Flash::error('Ppic not found');
            return redirect(route('report-daily-stock.index'));
        }

        return view('ppics.edit')->with('ppic', $ppic)
            ->with('report_id',$report_id)
            ->with('type_id', $type_id)
            ->with('type_name', $type_name)
            ->with('outstanding', $outstanding);
    }

    /**
     * Update the specified ppic in storage.
     *
     * @param int $id
     * @param UpdateppicRequest $request
     *
     * @return Response
     */
    public function update($id, UpdateppicRequest $request)
    {
        $ppic = $this->ppicRepository->find($id);
        $input = $request->all();

        if (empty($ppic)) {
            Flash::error('Ppic not found');

            return redirect(route('report-daily-stock.index'));
        }
        $timestamp = time(); // Timestamp saat ini, Anda juga bisa menggunakan timestamp lain
        $input['last_update'] = date('Y-m-d H:i:s', $timestamp);

        $this->ppicRepository->update($input, $id);


        // $input3 = array (
        //     'departement'=>'ppic',
        //     'tanggal' => date('Y-m-d'),
        //     'status' => $ppic_status,
        //     'message' => $ppic_typename . ' | PURCHASING feedback',
        //     'ppic_id' => $ppicid,
        //     'is_read' => 'F',
        // );
        // $this->notificationRepository->create($input3);

        // notif purchasing jika ppic failed
        $ppic = $this->ppicRepository->find($id);
        if($ppic->status == 'failed' && $ppic->notify_purchasing == 'y') {
            $input2 = array (
                'departement'=>'purchasing',
                'tanggal' => $ppic->tanggal,
                'message' => $ppic->type->nama . ' | '.$ppic->keterangan,
                'status' => $ppic->keterangan,
                'ppic_id' => $ppic->id,
                'is_read' => 'F',
            );
            // $notifications = $this->notificationRepository->all();
            // $notifications = $notifications->where('ppic_id', $ppic->id);
            // if ($notifications->count() == 0)
            $this->notificationRepository->create($input2);
        }   


        $input['ppic_id'] = $id;
        $input['user_id'] = $request->user()->id;
        $ppicLog = $this->ppicLogRepository->create($input);

        Flash::success('Ppic updated successfully.');

        return redirect(route('report-daily-stock.index'));
    }

    /**
     * Remove the specified ppic from storage.
     *
     * @param int $id
     *
     * @throws \Exception
     *
     * @return Response
     */
    public function destroy($id)
    {
        $ppic = $this->ppicRepository->find($id);

        if (empty($ppic)) {
            Flash::error('Ppic not found');

            return redirect(route('report-daily-stock.index'));
        }

        $this->ppicRepository->delete($id);

        Flash::success('Ppic deleted successfully.');

        return redirect(route('report-daily-stock.index'));
    }

    function generateNoTransaksi($tanggal) {
        $year = substr($tanggal, 0, 4);
        $month = substr($tanggal, 5, 2);
        $otherRencana = DB::table('ppics')
            ->whereYear('tanggal', $year)
            ->whereMonth('tanggal', $month)
            ->orderBy('no_transaksi', 'desc')
            ->first();

        $urutanTanggal = str_replace("-", "", $tanggal);
        $key0 = "PP-";
        $key1 = substr($urutanTanggal, 2, 2);
        $key2 = substr($urutanTanggal, 4, 2);
        if (!$otherRencana) {
            $no_transaksi = sprintf("%04d", 1);
            $no_transaksi  = $key0.$key1.$key2."-".$no_transaksi;
        } else {
            $prevUrutan = substr($otherRencana->no_transaksi, -3);
            $prevUrutan = (int) $prevUrutan;
            $no_transaksi = sprintf("%04d", $prevUrutan + 1);
            $no_transaksi  =  $key0.$key1.$key2."-".$no_transaksi;
        }
        return $no_transaksi;
    }

    public function close_ppic(Request $request) {
		// validasi
		// menangkap file excel
        $input = $request->all();
        $ids = $input['ids'];

        foreach ($ids as $id) {
            $report = $this->reportDailyStockRepository->find($id);
            if ($report->ppic_id) {
                $inputdata = array(
                    "status" => 'closed'
                );
                $this->ppicRepository->update($inputdata, $report->ppic_id);
            }
        }
        

        $response = [
            "message"=> "success"
        ];
        return response()->json($response);
	}

    function createPPIC($type_id, $outstanding, $user) {
        // cari ppic terakhir dan cek statusnya
        // jika statusnya belum close pake untuk ppice berikutnya
        $tanggal = date('Y-m-d');
        $timestamp = time(); // Timestamp saat ini, Anda juga bisa menggunakan timestamp lain
        $data = array(
            'tanggal' => $tanggal,
            'type_id' => $type_id,
            'outstanding_stok' => $outstanding,
            'status' => 'Waiting Response',
            'last_update' => date('Y-m-d H:i:s', $timestamp),
            'no_transaksi' => $this->generateNoTransaksi($tanggal)
        );

        // cari ppic terakhir dan cek statusnya
        // jika statusnya belum close pake untuk ppice berikutnya
        $ppics = $this->ppicRepository->allQuery();
        $prevPPIC = $ppics->where('type_id', $type_id)->orderBy('id', 'DESC')->first();
        if ($prevPPIC && ($prevPPIC->status === 'On Schedule' || $prevPPIC->status === 'failed')) {

resources/views/ppics/comment_table.blade.php
<div class="table-responsive">
    <table class="table" id="ppicComments-table">
        <thead>
            <tr>
                <th style="width: 15%">Nama</th>
                <th>Keterangan</th>
                <!-- <th colspan="3">Action</th> -->
            </tr>
        </thead>
        <tbody>
        @foreach($ppicComments as $ppicComment)
            <tr>
            <td>{{ $ppicComment->user ? $ppicComment->user->name : $ppicComment->user_id }}</td>
            
            <td>{{ $ppicComment->keterangan }}</td>
                <!-- <td>
                    {!! Form::open(['route' => ['ppicComments.destroy', $ppicComment->id], 'method' => 'delete']) !!}
                    <div class='btn-group'>
                        <a href="{{ route('ppicComments.show', [$ppicComment->id]) }}" class='btn btn-default btn-xs'><i class="glyphicon glyphicon-eye-open"></i></a>
                        <a href="{{ route('ppicComments.edit', [$ppicComment->id]) }}" class='btn btn-default btn-xs'><i class="glyphicon glyphicon-edit"></i></a>
                        {!! Form::button('<i class="glyphicon glyphicon-trash"></i>', ['type' => 'submit', 'class' => 'btn btn-danger btn-xs', 'onclick' => "return confirm('Are you sure?')"]) !!}
                    </div>
                    {!! Form::close() !!}
                </td> -->
            </tr>
        @endforeach
        </tbody>
    </table>
</div>

resources/views/ppics/create.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            PPIC
        </h1>
    </section>
    <div class="content">
        @include('adminlte-templates::common.errors')
        <div class="box box-primary">
            <div class="box-body">
                <div class="row">
                    {!! Form::open(['route' => 'ppics.store']) !!}

                        @include('ppics.fields')

                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
@endsection

@section('scripts')
    <script type="text/javascript">
        var today = new Date();
        $('#tanggal').val(today.toISOString().substr(0, 10));
    </script>
@endsection

resources/views/ppics/edit.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Ppic
        </h1>
   </section>
   <div class="content">
       @include('adminlte-templates::common.errors')
       <div class="box box-primary">
           <div class="box-body">
               <div class="row">
                   {!! Form::model($ppic, ['route' => ['ppics.update', $ppic->id], 'method' => 'patch']) !!}

                        @include('ppics.fields')

                   {!! Form::close() !!}
               </div>
           </div>
       </div>
   </div>
@endsection

resources/views/ppics/fields.blade.php
<div class="form-group col-sm-6">
    {!! Form::label('report_id', 'Report No:') !!}
    {!! Form::text('', (isset($ppic)) ? $ppic->no_transaksi : null, ['class' => 'form-control', 'id'=>'search_type', 'readonly' => 'true']) !!}
    {!! Form::hidden('report_id', $report_id, ['class' => 'form-control', 'id'=>'search_type', 'readonly' => 'true']) !!}
</div>

<div class="form-group col-sm-6">
    {!! Form::label('type_id', 'Type Name:') !!}
    {!! Form::text('', $type_name, ['class' => 'form-control', 'id'=>'search_type', 'readonly' => 'true']) !!}

    {!! Form::hidden('type_id', $type_id, ['class' => 'form-control', 'id'=>'search_type', 'readonly' => 'true']) !!}
</div>

<!-- Outstanding Stok Field -->
<div class="form-group col-sm-6">
    {!! Form::label('outstanding_stok', 'Outstanding Stok:') !!}
    {!! Form::number('outstanding_stok', $outstanding, ['class' => 'form-control', 'readonly' => 'true']) !!}
</div>


<!-- Tanggal Field -->
<div class="form-group col-sm-6">
    {!! Form::label('tanggal', 'Tanggal:') !!}
    {!! Form::date('tanggal', (isset($ppic)) ? $ppic->tanggal : null, ['class' => 'form-control','id'=>'tanggal']) !!}
</div>

<!-- Type Id Field -->
<!-- <div class="form-group col-sm-6">
{!! Form::label('type_id', 'ID Tipe & Nama Tipe:') !!}
    {!! Form::text('', $type_id, ['class' => 'form-control', 'id'=>'search_type',
            'readonly' => (isset($ppic) and $ppic->status == 'aktual') ? true : false]) !!}
    {!! Form::text('type_id', (isset($ppic)) ? $ppic->type_id : null, ['class' => 'form-control','id'=>'type_id', 'readonly' => 'true', 'placeholder' => 'ID']) !!}
    {!! Form::text('nama', (isset($ppic)) ? $ppic->nama : null, ['class' => 'form-control','id'=>'type_name', 'readonly' => 'true', 'placeholder' => 'Tipe']) !!}
</div> -->

<!-- Status Field -->
<div class="form-group col-sm-6">
    {!! Form::label('status', 'Status:') !!}
    {!! Form::select('status', ['Waiting Response' => 'Waiting Response', 
        'On Schedule' => 'On Schedule', 
        'delay' => 'Delay', 
        'failed' => 'Failed', 'closed' => 'Closed'], null, ['class' => 'form-control', 'id'=>'requiredSource']) !!}
</div>

<!-- Tanggal Produksi Field -->
<div class="form-group col-sm-6">
    {!! Form::label('tanggal_produksi', 'Selesai Produksi:', ['class' => 'labeltanggal']) !!}
    {!! Form::date('tanggal_produksi',  (isset($ppic->tanggal_produksi)) ? $ppic->tanggal_produksi : null, ['class' => 'form-control ','id'=>'tanggal_produksi']) !!}
</div>

<div class="form-group col-sm-6">
    {!! Form::label('notify_purchasing', 'Notify Purchasing:') !!}
    {!! Form::select('notify_purchasing', [
        'y' => 'Yes', 
        'n' => 'No', 
    ], null, ['class' => 'form-control']) !!}
</div>


<!-- Keterangan Field -->
<div class="form-group col-sm-12">
    {!! Form::label('keterangan', 'Keterangan / Alasan:',['class' => 'labelketerangan'] )  !!}
    {!! Form::textarea('keterangan', null, ['class' => 'form-control','id'=>'keterangan']) !!}
</div>




<!-- Submit Field -->
<div class="form-group col-sm-12">
    {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
    <a href="{{ route('report-daily-stock.index') }}" class="btn btn-default">Cancel</a>
</div>

@section('scripts')
    <script type="text/javascript">
        $('#requiredSource').change(function() {
            if($(this).val() == 'On Schedule')
            {
              $('#tanggal_produksi').attr('required', 'true');
              $('.labeltanggal').html("Tanggal Produksi: **");
              $('.labeltanggal').css('color', 'red');
            }
            else if($(this).val() == 'failed')
            {
              $('#keterangan').attr('required', 'true');
              $('.labelketerangan').html("Keterangan: **");
              $('.labelketerangan').css('color', 'red');
            }
            else
            {
              $('#tanggal_produksi').removeAttr('required');
              $('.labeltanggal').html("Tanggal Produksi:");
              $('.labeltanggal').css('color', 'black');
            }
        });
        
    </script>
@endsection

resources/views/ppics/logs_table.blade.php
<div class="table-responsive">
    <table class="table" id="ppicLogs-table">
        <thead>
            <tr>
                <th>Tanggal</th>
                <th>Type</th>
                <th>Outstanding Stok</th>
                <th>Status</th>
                <th>Selesai Produksi</th>
                <th>Keterangan</th>
                <th>User</th>
                <!-- <th colspan="3">Action</th> -->
        </tr>
        </thead>
        <tbody>
        @foreach($ppicLogs as $ppicLog)
            <tr>
                <td>{{ $ppicLog->tanggal->format('d/m/Y') }}</td>
                <td>{{ $ppicLog->type->nama }}</td>
                <td>{{ $ppicLog->outstanding_stok }}</td>
                <td>{{ $ppicLog->status }}</td>
                <td>{{ $ppicLog->tanggal_produksi }}</td>
                <td>{{ $ppicLog->keterangan }}</td>
                <td>{{ $ppicLog->user ? $ppicLog->user->name : '-' }}</td>
                <!-- <td>
                    {!! Form::open(['route' => ['ppicLogs.destroy', $ppicLog->id], 'method' => 'delete']) !!}
                    <div class='btn-group'>
                        <a href="{{ route('ppicLogs.show', [$ppicLog->id]) }}" class='btn btn-default btn-xs'><i class="glyphicon glyphicon-eye-open"></i></a>
                        <a href="{{ route('ppicLogs.edit', [$ppicLog->id]) }}" class='btn btn-default btn-xs'><i class="glyphicon glyphicon-edit"></i></a>
                        {!! Form::button('<i class="glyphicon glyphicon-trash"></i>', ['type' => 'submit', 'class' => 'btn btn-danger btn-xs', 'onclick' => "return confirm('Are you sure?')"]) !!}
                    </div>
                    {!! Form::close() !!}
                </td> -->
            </tr>
        @endforeach
        </tbody>
    </table>
</div>

resources/views/ppics/show.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Ppic
        </h1>
    </section>
    <div class="content">
        <div class="box box-primary">
            <div class="box-body">
                <div class="row" style="padding-left: 20px">
                    @include('ppics.show_fields')
                    <a href="{{ route('report-daily-stock.index') }}" class="btn btn-default">Back</a>
                </div>
            </div>
        </div>

        <div class="box box-primary">
            <h4 class="title-box">LOG DATA</h4>
            <div class="box-body">
                <div class="row" style="padding-left: 20px">
                    @include('ppics.logs_table')
                </div>
            </div>
        </div>

        <div class="box box-primary">
            <h4 class="title-box">DISKUSI</h4>
            <div class="box-body">
                <div class="row" style="padding-left: 20px">
                    @include('ppics.comment_table')
                </div>
            </div>
            <div class="form-group"  >
                <div class="modal-footer">
                    <a class="btn btn-primary pull-right" style="margin-top: -10px;margin-bottom: 5px" 
                        href="{{ route('ppicComments.create') }}?ppic_id={{$ppic->id}}&ppic_status={{$ppic->status}}&ppic_sum={{$ppic->outstanding_stok}}&&ppic_typename={{ $ppic->type->nama }}">Buat Komentar</a>
                </div>
            </div>
        </div>
    </div>
@endsection